feat: write test for anthropic tracing (compilation error occurs)
Receive the following error:
```
java.lang.IllegalStateException: `Expect/actual declaration for `withTrace` not found. Found: [FUN IR_EXTERNAL_DECLARATION_STUB name:withTrace visibility:public modality:FINAL <T> (function:kotlin.reflect.KFunction<*>, args:kotlin.Array<kotlin.Any?>, block:kotlin.Function0<T of ai.dev.kit.tracing.fluent.processor.withTrace>) returnType:T of ai.dev.kit.tracing.fluent.processor.withTrace [inline], FUN IR_EXTERNAL_DECLARATION_STUB name:withTrace visibility:public modality:FINAL <T> (function:kotlin.reflect.KFunction<*>, args:kotlin.Array<kotlin.Any?>, block:kotlin.Function0<T of ai.dev.kit.tracing.fluent.processor.withTrace>) returnType:T of ai.dev.kit.tracing.fluent.processor.withTrace [inline]]
```